# GENERATED FILE - DO NOT EDIT.
# Source: scripts/Sync-ProviderResourceCoverage.ps1
# Provider: helm
# Module: release/resources/helm_release
# File: main.tf
# SPDX-License-Identifier: MIT
resource "helm_release" "this" {
  count                      = var.enabled ? 1 : 0
  chart                      = var.chart
  name                       = var.name
  atomic                     = var.atomic
  cleanup_on_fail            = var.cleanup_on_fail
  create_namespace           = var.create_namespace
  dependency_update          = var.dependency_update
  description                = var.description
  devel                      = var.devel
  disable_crd_hooks          = var.disable_crd_hooks
  disable_openapi_validation = var.disable_openapi_validation
  disable_webhooks           = var.disable_webhooks
  force_update               = var.force_update
  keyring                    = var.keyring
  lint                       = var.lint
  max_history                = var.max_history
  namespace                  = var.namespace
  pass_credentials           = var.pass_credentials
  postrender                 = var.postrender
  recreate_pods              = var.recreate_pods
  render_subchart_notes      = var.render_subchart_notes
  replace                    = var.replace
  repository                 = var.repository
  repository_ca_file         = var.repository_ca_file
  repository_cert_file       = var.repository_cert_file
  repository_key_file        = var.repository_key_file
  repository_password        = var.repository_password
  repository_username        = var.repository_username
  reset_values               = var.reset_values
  reuse_values               = var.reuse_values
  set                        = var.set
  set_list                   = var.set_list
  set_sensitive              = var.set_sensitive
  set_wo                     = var.set_wo
  set_wo_revision            = var.set_wo_revision
  skip_crds                  = var.skip_crds
  take_ownership             = var.take_ownership
  timeout                    = var.timeout
  timeouts                   = var.timeouts
  upgrade_install            = var.upgrade_install
  values                     = var.values
  verify                     = var.verify
  version                    = var.version
  wait                       = var.wait
  wait_for_jobs              = var.wait_for_jobs
}
