data "gitlab_project_issues" "this" {
  count                 = var.enabled ? 1 : 0
  project               = var.project
  assignee_id           = var.assignee_id
  assignee_username     = var.assignee_username
  author_id             = var.author_id
  confidential          = var.confidential
  created_after         = var.created_after
  created_before        = var.created_before
  due_date              = var.due_date
  iids                  = var.iids
  issue_type            = var.issue_type
  labels                = var.labels
  milestone             = var.milestone
  my_reaction_emoji     = var.my_reaction_emoji
  not_assignee_id       = var.not_assignee_id
  not_author_id         = var.not_author_id
  not_labels            = var.not_labels
  not_milestone         = var.not_milestone
  not_my_reaction_emoji = var.not_my_reaction_emoji
  order_by              = var.order_by
  scope                 = var.scope
  search                = var.search
  sort                  = var.sort
  updated_after         = var.updated_after
  updated_before        = var.updated_before
  weight                = var.weight
  with_labels_details   = var.with_labels_details
}
